### ISSUE TITLE
SPIKE: for BCeID user, can we get first name, last name and email information from the attribute mapping

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1388] opened 2024-05-14 22:12 UTC
**Describe the task**
Check if the BCeID attribute mapping can be updated to include first name, last name and email information in the token. 

**Acceptance Criteria**
- [x] Find out if it's possible to update the attribute mapping
- [ ] Check Cognito attributes that need to be updated
- [ ] Check Pathfinder SSO attributes that need to be updated 

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment] 2024-05-16 19:26
Based on SSO [Identity Provider Attribute Mapping](https://github.com/bcgov/sso-keycloak/wiki/Identity-Provider-Attribute-Mapping).
(First Name/Last Name) will not be provided for BCeID account.
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/0d6289c3-4a03-4cf9-ada9-f27ec3d163b0)

We should probably use Business Legal Name.

**Comment by OlgaLiber2** [comment] 2024-05-17 15:34
@ianliuwk1019 we need to find out then how we can display first and last names of BCeID users. Business name does not make sense in this case.

**Comment by ianliuwk1019** [comment] 2024-05-17 21:00
Reply from Conrad:

![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/d3f302ee-dcfd-4a77-b600-75b979ae5c45)

**Comment by OlgaLiber2** [comment] 2024-05-17 21:04
@ianliuwk1019 whatever we need to do to make it happen. Does it make sense to get Conrad to help us with it?

**Comment by ianliuwk1019** [comment] 2024-05-17 22:51
Also confirmed with SSO team. These fields are not available and can't be customizable.
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/768c124c-f1ed-4199-9e8b-c9058a4b8b98)

**Comment by ianliuwk1019** [comment] 2024-05-17 22:58
Hi @OlgaLiber2 
I think we are trying to exploring the possibility to get first_name and last_name from Cognito for BCeID users.
The purpose I think is that we can get these information from the token so we can update into our FAM user table when user login again.
Since that's not possible from the Pathfinder SSO, we could still update to our FAM user table since we have the IDIM search already 
(it just a bit inconvenient).

If we would have to have these information in the BCeID user token for some more critical business reasons, and as Conrad said to skip Pathfinder SSO and go directly to SiteMinder, that would be a architectural change on design and also big implementation change I think, also some political issues Conrad mentioned.
@basilv

**Comment by ianliuwk1019** [comment] 2024-05-21 19:26
Closed this spike as it is confirmed we will not be able to get these attributes from Pathfinder SSO; mentioned and discussed with team.

**Comment by ianliuwk1019** [comment] 2024-06-04 22:22
Provide more background of the reasons why SSO Pathfinder does not provide first/last names (from Conrad):
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/411b749a-47cc-4846-b0d0-bf102f3ca1ea)
FYI @OlgaLiber2

**Comment by OlgaLiber2** [comment] 2024-06-04 22:48
Thanks for closing the loop on this, @ianliuwk1019. Let's update our code to read the attributed directly form BCeID. 
Let me know what needs to happen next and how I can help.

**Comment by ianliuwk1019** [comment] 2024-06-04 23:12
Hi @OlgaLiber2 , I am sensing maybe that bring confusion to you.

For our FAM, our code don't need to worry getting first/last names as we already can get these information for IDIR/BCeID users from IDIM web service.
We tried to explore if we could get this from Cognito (provided by SSO Pathfinder) so that we can provide first/last names in "**ID token**" and also benefit for use at one-time load (or periodically) refresh our FAM user table.

For displaying first/last names in FAM for frontend manage-permission page (or other pages), they will be coming from our user table (which we will record first/last names in our database, through IDIM webservice search).

We can create a ticket to explore integration through SiteMinder (I think that's what I understand, the source of truth, for directly from BCeID) for Cognito integration, to bypass SSO Pathfinder; but without this, it does not impact our code to be done.

But, there is one concerns, it seems to me, other teams cannot rely on the ID token "displayName" as suggested (to split it into first/last names), and if the recommended approach is for other teams also to integrate search through IDIM webservice, it might be too much for other teams to do that (if they don't currently have that search ability or policy with IDIM).
@basilv

**Comment by basilv** [comment] 2024-06-04 23:38
We could potentially augment our tokens with first/last name from our database.

**Comment by ianliuwk1019** [comment] 2024-06-04 23:53
Thanks @basilv !!
Yes, that's what I have been thinking about the possibility.
After we have the cron job to refreshing our FAM user table, at the same time we can grab the first/last name and update them.
Except the **very first login** and **before** the cron job run, then the token will have no first/last name values.
However, hopefully the post-auth won't reach the Cognito timeout limit and, I am not clear if the post-auth can add these attribute to ID Token (currently if I understand is on Access Token).

**Comment by ianliuwk1019** [comment] 2024-06-05 17:14
Ahhh~~ I read further and got what you meant ("augment our token") @basilv !
We can customize ID Token using "[Pre token generation Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html)" to supply the first/last names to ID Token.
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/8d9978b7-6dc9-4bd6-a83e-f2bbac4371f7)

**Closed** 2024-07-17 23:08 UTC
Labels: Story: display user info
