### ISSUE TITLE
Create a FAM role for the FOM Access Administrator

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#195] opened 2022-09-20 18:31 UTC
As a FOM access administrator, I want to have roles that I can assign users to on FOM, so that I am able to provision access. 

AC:
Use an Insert statement to create "FOM Access Administrator"

* follow steps identified [here](https://github.com/bcgov/nr-forests-access-management/blob/dev/server/backend/api/alembic/readme.md) to create:
  * an alembic migration 
  * from the alembic migration create the flyway migration
  * verify the flyway migration sql

**Comment by ConradBoydElliottGustafson** [comment] 2022-11-04 17:14
@gormless87 This is a duplicate of 155 (subset actually)

**Comment by ConradBoydElliottGustafson** [comment] 2022-11-10 01:07
Duplicate of #155

**Closed by ConradBoydElliottGustafson** 2022-11-10 01:07 UTC
Labels: mvp1.0
