### ISSUE TITLE
Front-end Integrate with Forest Client API

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#179] opened 2022-09-07 21:10 UTC
As a an application access administrator I want to see a list of forest client So That I can select a forest client for an assignment.

Additional Context
-- Integrate Forest Client API with frontend and back-end for validation.
--Allow users to select and search for a forest client by forest client name and ID.
--If Forest Client does not exists, return a message "Forest Client cannot be Found".

**Acceptance Criteria**
When I type in a FC ID I want validation (via API) and see company name 

**Definition of Done**
 Ready to Demo in Sprint Review
 Does what I have made have appropriate test coverage?
 Documentation and/or scientific documentation exists and can be found
 Peer Reviewed by 2 people on the team
 Manual testing of all PRs in Dev and Prod
 Merged

**Comment by ianliuwk1019** [comment] 2022-10-19 14:26
Current backend has "**Create User/Role Assignment**" **endpoint** done for the first draft version which takes "**forest client number**" as is as parameter in request body (without forest client name). Saving the record into fam_forest_client "client_name" column is currently hardcoded dummy data.

When we start integration with Forest Client API, backend endpoint logic will needs some adjustment to:
- Validate "**forest_client_number**" parameter sent is correct by checking with Forest Client API.
- Obtain Forest Client "name" from Forest Client API to save into the database record's **client_name** column.

**Comment by basilv** [comment] 2022-10-19 14:30
I'm unsure of the design to store the client name - which table is that again?

**Comment by ianliuwk1019** [comment] 2022-10-19 14:39
The '**client_name**' column is at fam_forest_client table.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/6d2f91b2-ff5a-4b48-a27f-5690f5b35585)

**Comment by basilv** [comment] 2022-10-19 15:02
It seems weird to update this table from individual add-role-assignment transactions

**Comment by basilv** [comment] 2022-10-19 17:10
As discussed in today's scrum - plan is to have FAM backend retrieve forest client name from forest client API and store in this table as part of add-role-assignment transaction. 

Also, FAM front-end will need to search/look up forest clients, which will need to go through a FAM backend API to call system-to-system to forest client API using secure token.

**Comment by ianliuwk1019** [comment] 2023-03-20 16:46
I am not sure why the `client_name` column were being removed from the `fam_forest_client` table (might be due to we had no forest client api integration last year)
We might need to see if there is a need to use Forest Client Name for display in FAM (and bring back the column/logic). For example on this screen (or any other page in future):
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/1a5b67db-b54d-4bf2-9277-427ce1e30d9b)

Option1 - save `forest_client_name` when role assignment is created. Will be easier later to display. However, name may changed in future.
Option2 - frontend will need to loop though forest client data retrieved from forest client api (by id) and display the name. Will be extra trip to the api and slow.
Depending on future design.
@basilv @OlgaLiber2

**Comment by basilv** [comment] 2023-03-20 17:00
I beilieve we removed the client names because the column was mandatory and causing problems for granting access (e.g. we were populating with 'fake' names'), and we didn't have a design for displaying them anyways.

**Comment by ianliuwk1019** [comment] 2023-03-20 19:30
Hi @OlgaLiber2 ,
Do you have screenshot of what frontend would expect for the (**Phase 1** on backend ticket - #305)?
That will help if team does have clear vision of what phase 1 vision and implementation would be (both frontend and backend).
Currently this is the input box with entering 8 digits forest client id.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/d07d69a8-c8af-4858-b105-8426c4107a40)

From the Forest Client API itself, there is only exact match - whole correct id number entered in the input box (I think Catherine mentioned that last week) possible for now.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/e1b6bf7f-7622-4c12-b4a7-41b2f50e7a37)
So for our FAM, we currently won't be able to do "**Search**" at the frontend input from my understanding.
We can currently do:
- Validation at backend when user enter **id** (and only id): return empty data (no match), or only one forest client information (if matched with "**id**").
- This information can be sent back to frontend for display message.
- Validation at backend again when granting user role access (when forest client is involved).

If above points are correct (fore **Phase 1**), both frontend/backend Forest Client Api integration tickets for phase 1 will need to be changed for description and acceptance.

@basilv @ArogeG @gormless87

**Comment by ianliuwk1019** [comment] 2023-03-20 20:32
Greatly appreciate your comments here @basilv . Thank you.
I will work toward "validation" only (plus a new temporary endpoint for frontend to be able to get this client information at frontend by id, this endpoint will be adjusted based on Olga's future design.)

**Comment by basilv** [comment] 2023-03-20 20:33
Irrespective of phase 1 / 2, there are some business rules we need to clarify. @ArogeG @OlgaLiber2 
- Are all types of forest clients (clientTypeCode) considered valid, or should certain types (like Individual) be considered 'not valid'. (FOM is only set up with non-individual forest clients and has confirmed needing more than just corporations, but I don't know what other apps might want to do. )
The full list of types seems to be: A (Association),B (First Nation Band),C (Corporation),F (Ministry of Forests and Range),G (Government),I (Individual),L (Limited Partnership),P (General Partnership),R (First Nation Group),S (Society),T (First Nation Tribal Council),U (Unregistered Company),Z (Sole Proprietorship)
- Do we care about the client status code? E.g. does the API only return active (ACT?) codes, or can it return clients in other states (e.g. inactive). If we get back inactive clients, I assume we should reject them for granting access. If a client becomes inactive after being granted access, should we check this during auth login and disallow the access?
- We should confirm that FAM will just display the 'clientName' field and not the legal first name, middle name.  (It appears clientName could be either an organization or a client's last name, based on the sample from the forest client API ?)
   {  "clientName": "BAXTER", "legalFirstName": "JAMES", "legalMiddleName": "Canter",   "clientStatusCode": "ACT", 
    "clientTypeCode": "I" }

**Comment by basilv** [comment] 2023-03-28 18:13
@ArogeG @OlgaLiber2 So apparently there are 5 possible statuses in forest client: Active, Deactivated, Deceased, Receivership, and Suspended. Should all of these statuses be accepted?

**Comment by basilv** [comment] 2023-03-28 18:18
Based on discussion with Olga in teams: So the logic you want is:

if status from forest client = Active then display Active

else display Inactive

**Comment by basilv** [comment] 2023-03-28 18:56
For validating forest client - only valid if status is active.
For lookup of forest client by front-end - return both active and inactive.

**Comment by basilv** [comment] 2023-03-28 19:13
So if status is not active then the forest client is considered invalid - do not proceed with granting access (in front-end or back-end).

**Comment by ianliuwk1019** [comment] 2023-03-29 21:00
Backend forest client integration is still in progress and in review (draft). However, the branch now can be pulled and be used **locally** for frontend to get forest client result if needed (branch: `feat/305-forestClientAPI-backend-integration`). Also see comment in ticket #305.
**Note!** Do not merge backend into frontend working branch, can create separate branch to test it out. 
@NickSaglioni

**Comment by ianliuwk1019** [comment] 2023-04-21 14:10
Backend ticket #305 is done and merged to main.
Frontend is unblocked from #305.
Hello @NickSaglioni , you can pull from main but before pulling please remember (and don't commit) the API token (TEST environment) from backend api. It is currently at your local backend config.py but will be gone once merged from main branch.
You can set it locally to backend `local-dev.env' with key `FC_API_TOKEN=[api-token]` but don't commit it.
Thank you.

**Closed** 2023-05-02 17:46 UTC
Labels: mvp1.1, FAM 1.1
