### ISSUE TITLE
FAM-API - Add User to Role

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#57] opened 2022-07-07 16:59 UTC
* GET /User/<userid>/Roles - to list roles the user has been granted
* POST /User/<userid>/Roles - add a user to a new role

Do we want to also have or have instead:
* GET /Role/<roleid>/User - list the users that belong to this role
* POST /Role/<roleid>/User - add a user to the given role

relates to:
https://github.com/bcgov/nr-forests-access-management/issues/20

**Comment by explorertolu** [comment] 2022-08-09 17:11
Closing - This is a duplicate of ticket #56
https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/nr-forests-access-management/56

**Closed by explorertolu** 2022-08-09 17:11 UTC
